In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('Expanded_data_with_more_features.csv')
df.head()

C:\Users\Roman Prokopchuk\AppData\Local\Temp\ipykernel_15644\1042718370.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


Unnamed: 0  Gender EthnicGroup          ParentEduc     LunchType TestPrep  \
0           0  female         NaN   bachelor's degree      standard     none   
1           1  female     group C        some college      standard      NaN   
2           2  female     group B     master's degree      standard     none   
3           3    male     group A  associate's degree  free/reduced     none   
4           4    male     group C        some college      standard     none   

  ParentMaritalStatus PracticeSport IsFirstChild  NrSiblings TransportMeans  \
0             married     regularly          yes         3.0     school_bus   
1             married     sometimes          yes         0.0            NaN   
2              single     sometimes          yes         4.0     school_bus   
3             married         never           no         1.0            NaN   
4             married     sometimes          yes         0.0     school_bus   

  WklyStudyHours  MathScore  ReadingScore  WritingScore  
0            < 5         71            71            74  
1         5 - 10         69            90            88  
2            < 5         87            93            91  
3         5 - 10         45            56            42  
4         5 - 10         76            78            75

1) Скільки студентів і студенток у наборі даних?


In [3]:
male = df.query('Gender == "male"')['Gender'].count()
female = df.query('Gender == "female"')['Gender'].count()
print(f"Male = {male}, female = {female}")

Male = 15217, female = 15424


2. Який відсоток студентів чоловічої статі в наборі даних?

In [4]:
male * 100 / (male + female)

49.6622172905584

3. Який відсоток студенток у наборі даних?

In [5]:
female * 100 / (male + female)

50.3377827094416

4. Яка етнічна група має найвищий середній бал з математики?

In [6]:
df.groupby('EthnicGroup')["MathScore"].mean().sort_values(ascending=False)[:1]

EthnicGroup
group E    75.298936
Name: MathScore, dtype: float64

5. Яка етнічна група має найвищий середній бал читання?

In [7]:
df.groupby('EthnicGroup')["ReadingScore"].mean().sort_values(ascending=False)[:1]

EthnicGroup
group E    74.251423
Name: ReadingScore, dtype: float64

6. Яка етнічна група має найвищий середній бал з письма?

In [8]:
df.groupby('EthnicGroup')["WritingScore"].mean().sort_values(ascending=False)[:1]

EthnicGroup
group E    72.67706
Name: WritingScore, dtype: float64

7. Який середній бал з математики для студентів, які закінчили курс підготовки до тесту?

In [9]:
df.query("TestPrep == 'completed'")["MathScore"].mean()

69.5466599698644

8. Який середній бал з читання для студентів, які пройшли курс підготовки до тесту?

In [10]:
df.query("TestPrep == 'completed'")["ReadingScore"].mean()

73.73299849321948

9. Який середній бал для студентів, які закінчили курс підготовки до тесту?

In [11]:
df['MeanTestsScore'] = (df['MathScore'] + df['ReadingScore'] + df['WritingScore'])/3
df.query("TestPrep == 'completed'")["MeanTestsScore"].mean()

72.66097438473129

10. Скільки студентів мають одружених батьків?

In [12]:
df.query("ParentMaritalStatus == 'married'").count()['ParentMaritalStatus']

16844

11. Скільки студентів мають батьків-одинаків?

In [13]:
df.query("ParentMaritalStatus == 'single'").count()['ParentMaritalStatus']

7097

12. Чи студенти, які регулярно займаються спортом, мають вищі середні результати з математики, ніж ті, хто ніколи не займається спортом?

In [15]:
reg = df.query("PracticeSport == 'regularly'")["MathScore"].mean()
nev = df.query("PracticeSport == 'never'")["MathScore"].mean()
reg > nev

True

13. Чи студенти, які регулярно займаються спортом, мають вищі середні результати читання, ніж ті, хто ніколи не займається спортом?

In [16]:
reg = df.query("PracticeSport == 'regularly'")["ReadingScore"].mean()
nev = df.query("PracticeSport == 'never'")["ReadingScore"].mean()
reg > nev

True

14. Скільки учнів користується шкільним автобусом, щоб дістатися до школи?

In [17]:
df.query('TransportMeans == "school_bus"')['TransportMeans'].count()

16145

15. Скільки учнів користується приватним транспортом, щоб дістатися до школи?

In [18]:
df.query('TransportMeans == "private"')['TransportMeans'].count()

11362

## Задача класифікації

Передбачте, чи завершив студент курс підготовки до іспиту, на основі його демографічних та академічних даних. Вхідні дані: Gender, EthnicGroup, ParentEduc, LunchType, ParentMaritalStatus, PracticeSport, IsFirstChild, NrSiblings,       TransportMeans, WklyStudyHours, MathScore, ReadingScore, WritingScore. Результат: TestPrep

In [19]:
df = df.dropna()

In [20]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder()
X = ordinal_encoder.fit_transform(df.drop("TestPrep", axis=1))
X[:5]

array([[  2.,   0.,   1.,   3.,   1.,   2.,   2.,   1.,   4.,   1.,   1.,
         81.,  82.,  81., 219.],
       [  4.,   1.,   2.,   4.,   1.,   1.,   2.,   1.,   0.,   1.,   0.,
         70.,  67.,  65., 177.],
       [  5.,   0.,   1.,   0.,   1.,   1.,   1.,   1.,   1.,   1.,   0.,
         67.,  73.,  69., 184.],
       [  6.,   0.,   1.,   4.,   1.,   3.,   0.,   0.,   1.,   0.,   0.,
         79.,  82.,  79., 215.],
       [  7.,   1.,   1.,   4.,   0.,   1.,   2.,   1.,   1.,   0.,   2.,
         35.,  32.,  29.,  71.]])

In [21]:
y = np.array([0 if i == "none" else 1 for i in df["TestPrep"].values])
y[:5]

array([0, 0, 0, 1, 0])

In [22]:
len(X)

19243

In [23]:
len(y)

19243

In [24]:
X_train, X_test, y_train, y_test = X[:9000], X[9000:], y[:9000], y[9000:]

In [25]:
y_train_1 = (y_train == 1)

In [26]:
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(random_state=13)
sgd_clf.fit(X_train, y_train_1)

SGDClassifier(random_state=13)

In [27]:
sgd_clf.predict([X[130]])

array([False])

In [28]:
y[130]

1

In [29]:
from sklearn.model_selection import cross_val_score

cross_val_score(sgd_clf, X_train, y_train_1, cv=3, scoring="accuracy")

array([0.689     , 0.41766667, 0.479     ])

In [30]:
from tensorflow import keras

model = keras.models.Sequential([
    keras.layers.Dense(64, input_dim=X_train.shape[1], activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1)
])

C:\Dev_software\python\lib\site-packages\keras\src\layers\core\dense.py:86: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [31]:
X_valid, X_train_2 = X_train[:5000], X_train[5000:]
y_valid, y_train_2 = y_train[:5000], y_train[5000:]

In [32]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=["accuracy"])
model.fit(X_train, y_train, epochs=100, batch_size=32, verbose=1, validation_data=(X_valid, y_valid))

Epoch 1/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5158 - loss: 142.9411 - val_accuracy: 0.4926 - val_loss: 0.7372
Epoch 2/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5055 - loss: 0.7003 - val_accuracy: 0.5124 - val_loss: 0.4701
Epoch 3/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5287 - loss: 0.4580 - val_accuracy: 0.5698 - val_loss: 0.3196
Epoch 4/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5710 - loss: 0.3226 - val_accuracy: 0.5640 - val_loss: 0.2841
Epoch 5/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5984 - loss: 0.2922 - val_accuracy: 0.6392 - val_loss: 0.2714
Epoch 6/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6010 - loss: 0.2947 - val_accuracy: 0.6544 - val_loss: 0.5917
Epoch 7/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5979 - loss: 0.3142 - val_accuracy: 0.6488 - val_loss: 0.2299
Epoch 8/100
282/282 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6355 - loss: 0.2557 - val_ac

In [33]:
proba = model.predict(X_test[:4])
proba.round(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


array([[0.17],
       [0.23],
       [0.52],
       [0.29]], dtype=float32)

In [34]:
results = model.evaluate(X_test, y_test)
print(f"Test loss: {results[0]}, Test accuracy:{results[1]}")

321/321 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step - accuracy: 0.6812 - loss: 0.2182
Test loss: 0.22179099917411804, Test accuracy:0.6770477294921875


In [35]:
model = keras.models.Sequential([
    keras.layers.Dense(300, activation="relu"),
    keras.layers.Dense(100, activation="relu"),
    keras.layers.Dense(10, activation="softmax")
])

model.compile(loss="sparse_categorical_crossentropy", optimizer="sgd", metrics=["accuracy"])

history = model.fit(X_train_2, y_train_2, epochs=30, validation_data=(X_valid, y_valid))

Epoch 1/30
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5970 - loss: 441185.0312 - val_accuracy: 0.6542 - val_loss: 1.7795
Epoch 2/30
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6461 - loss: 1.6863 - val_accuracy: 0.6542 - val_loss: 1.4165
Epoch 3/30
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6596 - loss: 1.3293 - val_accuracy: 0.6542 - val_loss: 1.0999
Epoch 4/30
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6623 - loss: 1.0334 - val_accuracy: 0.6542 - val_loss: 0.9079
Epoch 5/30
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6496 - loss: 0.8827 - val_accuracy: 0.6542 - val_loss: 0.8052
Epoch 6/30
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6537 - loss: 0.7892 - val_accuracy: 0.6542 - val_loss: 0.7483
Epoch 7/30
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6537 - loss: 0.7396 - val_accuracy: 0.6542 - val_loss: 0.7167
Epoch 8/30
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6655 - loss: 0.7029 - val_accurac

In [36]:
proba = model.predict(X_test[:4])
proba.round(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[0.65, 0.34, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.65, 0.34, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.65, 0.34, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.65, 0.34, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]],
      dtype=float32)

In [37]:
y_pred = np.argmax(model.predict(X_test[:4]), axis=-1)
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([0, 0, 0, 0], dtype=int64)

In [38]:
y_test[:4]

array([0, 0, 1, 1])

In [39]:
y_test[:4] == y_pred

array([ True,  True, False, False])

In [40]:
results = model.evaluate(X_test, y_test)
print(f"Test loss: {results[0]}, Test accuracy:{results[1]}")

321/321 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step - accuracy: 0.6529 - loss: 0.6521
Test loss: 0.6568957567214966, Test accuracy:0.6522502899169922
