# Task 1

## Exercise 1
*Завдання*: Вводиться число n. Вивести масив розміру n×n, в якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [151]:
import numpy as np


def exercise_1_default(n):
    result = []

    for i in range(n):
        row = []

        for j in range(n):
            value_to_append = i + 1 if i == j else 0
            row.append(value_to_append)

        result.append(row)

    return result


def exercise_1_numpy(n):
    return np.diag(np.arange(1, n + 1, 1))


n = 10

print("=========Default=========")
%timeit -n 1000 gen_diagonal_matrix_default(n)

print("=========Numpy=========")
%timeit -n 1000 gen_diagonal_matrix_numpy(n)

print("=========Default result=========")
print(exercise_1_default(n))

print("=========Numpy result=========")
print(exercise_1_numpy(n))

=========Default=========
6.35 µs ± 61.1 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
2.01 µs ± 183 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 3, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 4, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 5, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 6, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 7, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 8, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 9, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 10]]
=========Numpy result=========
[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


## Exercise 3
*Завдання*: Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [152]:
def exercise_3_default(n, m, r, c):
    result = []

    for i in range(n):
        row = []

        for j in range(m):
            value_to_append = 0 if (i % r == 0 or j % c == 0) else 1
            row.append(value_to_append)

        result.append(row)

    return result


def exercise_3_numpy(n, m, r, c):
    result = np.ones((n, m), dtype=int)
    result[::r, :] = 0
    result[:, ::c] = 0

    return result


n, m, r, c = (6, 7, 2, 3)


print("=========Default=========")
%timeit -n 1000 exercise_3_default(n, m, r, c)

print("=========Numpy=========")
%timeit -n 1000 exercise_3_numpy(n, m, r, c)

print("=========Default result=========")
print(exercise_3_default(n, m, r, c))

print("=========Numpy result=========")
print(exercise_3_numpy(n, m, r, c))

=========Default=========
3.74 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
2.32 µs ± 55.3 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 1, 1, 0], [0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 1, 1, 0], [0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 1, 1, 0]]
=========Numpy result=========
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


## Exercise 4
*Завдання*: Вводяться числа n і m. Вивести масив розміру n×m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m–1, а всі інші елементи матриці дорівнюють 0.

In [153]:
def exercise_4_default(n, m):
    result = []

    for i in range(m):
        row_to_append = [idx for idx in range(n)] if i == 0 else [0] * n
        result.append(row_to_append)

    return result


def exercise_4_numpy(n, m):
    result = np.zeros((m, n), dtype=int)
    result[0] = np.arange(n)

    return result


n, m = (3, 4)

print("=========Default=========")
%timeit -n 1000 exercise_4_default(n, m)

print("=========Numpy=========")
%timeit -n 1000 exercise_4_numpy(n, m)

print("=========Default result=========")
print(exercise_4_default(n, m))

print("=========Numpy result=========")
print(exercise_4_numpy(n, m))

=========Default=========
795 ns ± 8.32 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
1.13 µs ± 177 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[0, 1, 2], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
=========Numpy result=========
[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


## Exercise 5
*Завдання*: Вводиться число n. Вивести масив розміру n×n, в якому в рядках з парними індексами стоять 1, а в інших – 0.

In [154]:
def exercise_5_default(n):
    result = []

    for i in range(n):
        row_to_append = ([1] if i % 2 == 0 else [0]) * n
        result.append(row_to_append)

    return result


def exercise_5_numpy(n):
    result = np.zeros((n, n), dtype=int)
    result[::2] = np.ones(n, dtype=int)

    return result


n = 5

print("=========Default=========")
%timeit -n 1000 exercise_5_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_5_numpy(n)

print("=========Default result=========")
print(exercise_5_default(n))

print("=========Numpy result=========")
print(exercise_5_numpy(n))

=========Default=========
760 ns ± 7.9 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
2.1 µs ± 519 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[1, 1, 1, 1, 1], [0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [0, 0, 0, 0, 0], [1, 1, 1, 1, 1]]
=========Numpy result=========
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]


## Exercise 10
*Завдання*: Вводиться числа n i m. Створити масив випадкових значень n×m і обчислити мінімальне, максимальне значення, середнє та середньо квадратичне відхилення, округлене до 3 знаків після коми.

In [155]:
def generate_random_matrix_default(n, m=n, upper_bound=100):
    result = []

    for i in range(n):
        row = []

        for j in range(m):
            row.append(np.random.randint(upper_bound))

        result.append(row)

    return result

# TODO: implement

## Exercise 12
*Завдання*: Створити масив одиниць розміром n×n та створити в ньому «рамку», що утворюється з 0.

In [156]:
def exercise_12_default(n):
    result = []

    for i in range(n):
        row_to_append = [0] * n if (i == 0 or i == n - 1) else [0] + [1] * (n - 2) + [0]
        result.append(row_to_append)

    return result


def exercise_12_numpy(n):
    result = np.ones((n, n), dtype=int)

    result[0] = np.zeros(n, dtype=int)
    result[-1] = np.zeros(n, dtype=int)
    result[:, 0] = np.zeros(n, dtype=int)
    result[:, -1] = np.zeros(n, dtype=int)

    return result

n = 5

print("=========Default=========")
%timeit -n 1000 exercise_12_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_12_numpy(n)

print("=========Default result=========")
print(exercise_12_default(n))

print("=========Numpy result=========")
print(exercise_12_numpy(n))

=========Default=========
1.04 µs ± 12.1 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
3.51 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[0, 0, 0, 0, 0], [0, 1, 1, 1, 0], [0, 1, 1, 1, 0], [0, 1, 1, 1, 0], [0, 0, 0, 0, 0]]
=========Numpy result=========
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


## Exercise 16
*Завдання*: Заповнити вектор значеннями від 0 до n. Всі значення, що більші за n/4 та менші за 3n/4 замінити нулями.

In [157]:
def exercise_16_default(n):
    return [0 if (n / 4 < i < (3 * n) / 4) else i for i in range(n + 1)]


def exercise_16_numpy(n):
    result = np.arange(n + 1)
    result[(result > n / 4) & (result < (3 * n) / 4)] = 0

    return result

n = 10

print("=========Default=========")
%timeit -n 1000 exercise_16_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_16_numpy(n)

print("=========Default result=========")
print(exercise_16_default(n))

print("=========Numpy result=========")
print(exercise_16_numpy(n))

=========Default=========
1.28 µs ± 5.66 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
3.63 µs ± 306 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[0, 1, 2, 0, 0, 0, 0, 0, 8, 9, 10]
=========Numpy result=========
[ 0  1  2  0  0  0  0  0  8  9 10]


## Exercise 17
*Завдання*: Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значень, що менші за n/2 та більші за 3n/4 на протилежні.

In [158]:
def exercise_17_default(n):
    return [-1 * i if (i < n / 2 or i > (3 * n) / 4 ) else i for i in range(n + 1)]


def exercise_17_numpy(n):
    result = np.arange(n + 1)
    result[(result < n / 2) | (result > (3 * n) / 4)] *= -1

    return result

n = 10

print("=========Default=========")
%timeit -n 1000 exercise_17_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_17_numpy(n)

print("=========Default result=========")
print(exercise_17_default(n))

print("=========Numpy result=========")
print(exercise_17_numpy(n))

=========Default=========
1.32 µs ± 117 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
5.08 µs ± 887 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[0, -1, -2, -3, -4, 5, 6, 7, -8, -9, -10]
=========Numpy result=========
[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]


# Exercise 21
*Завдання*: Ввести числа n і m. Згенерувати матрицю n×n випадкових цілих елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці на протилежні за знаком.

In [159]:
def exercise_21_default(n, m):
    matrix = generate_random_matrix_default(n, n, m)

    print("Matrix:")
    print(matrix)

    max_elem = max(max(matrix[i]) for i in range(n))

    for i in range(n):
        for j in range(n):
            if matrix[i][j] == max_elem:
                matrix[i][j] *= -1

    print("Changed matrix:")
    print(matrix)


def exercise_21_numpy(n, m):
    matrix = np.random.randint(0, m + 1, size=(n, n))

    print("Matrix:")
    print(matrix)

    max_elem = np.max(matrix)
    matrix[matrix == max_elem] *= -1

    print("Changed matrix:")
    print(matrix)


n, m = (3, 100)


print("=========Default=========")
%time exercise_21_default(n, m)

print("=========Numpy=========")
%time exercise_21_numpy(n, m)

=========Default=========
Matrix:
[[42, 75, 55], [3, 1, 28], [11, 50, 61]]
Changed matrix:
[[42, -75, 55], [3, 1, 28], [11, 50, 61]]
CPU times: total: 0 ns
Wall time: 0 ns
=========Numpy=========
Matrix:
[[46 19 66]
 [15 56 60]
 [50 57 90]]
Changed matrix:
[[ 46  19  66]
 [ 15  56  60]
 [ 50  57 -90]]
CPU times: total: 0 ns
Wall time: 500 µs
