# Task 1

## Exercise 1
*Завдання*: Вводиться число n. Вивести масив розміру n×n, в якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [12]:
import numpy as np


def exercise_1_default(n):
    result = []

    for i in range(n):
        row = []

        for j in range(n):
            value_to_append = i + 1 if i == j else 0
            row.append(value_to_append)

        result.append(row)

    return result


def exercise_1_numpy(n):
    return np.diag(np.arange(1, n + 1, 1))


n = 10

print("=========Default=========")
%timeit -n 1000 exercise_1_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_1_numpy(n)

print("=========Default result=========")
print(exercise_1_default(n))

print("=========Numpy result=========")
print(exercise_1_numpy(n))

=========Default=========
6.39 µs ± 82.4 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
2.32 µs ± 774 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 3, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 4, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 5, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 6, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 7, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 8, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 9, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 10]]
=========Numpy result=========
[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


## Exercise 3
*Завдання*: Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [13]:
def exercise_3_default(n, m, r, c):
    result = []

    for i in range(n):
        row = []

        for j in range(m):
            value_to_append = 0 if (i % r == 0 or j % c == 0) else 1
            row.append(value_to_append)

        result.append(row)

    return result


def exercise_3_numpy(n, m, r, c):
    result = np.ones((n, m), dtype=int)
    result[::r, :] = 0
    result[:, ::c] = 0

    return result


n, m, r, c = (6, 7, 2, 3)


print("=========Default=========")
%timeit -n 1000 exercise_3_default(n, m, r, c)

print("=========Numpy=========")
%timeit -n 1000 exercise_3_numpy(n, m, r, c)

print("=========Default result=========")
print(exercise_3_default(n, m, r, c))

print("=========Numpy result=========")
print(exercise_3_numpy(n, m, r, c))

=========Default=========
3.83 µs ± 84 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
2.3 µs ± 61.6 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 1, 1, 0], [0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 1, 1, 0], [0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 1, 1, 0]]
=========Numpy result=========
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


## Exercise 4
*Завдання*: Вводяться числа n і m. Вивести масив розміру n×m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m–1, а всі інші елементи матриці дорівнюють 0.

In [14]:
def exercise_4_default(n, m):
    result = []

    for i in range(m):
        row_to_append = [idx for idx in range(n)] if i == 0 else [0] * n
        result.append(row_to_append)

    return result


def exercise_4_numpy(n, m):
    result = np.zeros((m, n), dtype=int)
    result[0] = np.arange(n)

    return result


n, m = (3, 4)

print("=========Default=========")
%timeit -n 1000 exercise_4_default(n, m)

print("=========Numpy=========")
%timeit -n 1000 exercise_4_numpy(n, m)

print("=========Default result=========")
print(exercise_4_default(n, m))

print("=========Numpy result=========")
print(exercise_4_numpy(n, m))

=========Default=========
771 ns ± 8.64 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
1.17 µs ± 196 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[0, 1, 2], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
=========Numpy result=========
[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


## Exercise 5
*Завдання*: Вводиться число n. Вивести масив розміру n×n, в якому в рядках з парними індексами стоять 1, а в інших – 0.

In [15]:
def exercise_5_default(n):
    result = []

    for i in range(n):
        row_to_append = ([1] if i % 2 == 0 else [0]) * n
        result.append(row_to_append)

    return result


def exercise_5_numpy(n):
    result = np.zeros((n, n), dtype=int)
    result[::2] = np.ones(n, dtype=int)

    return result


n = 5

print("=========Default=========")
%timeit -n 1000 exercise_5_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_5_numpy(n)

print("=========Default result=========")
print(exercise_5_default(n))

print("=========Numpy result=========")
print(exercise_5_numpy(n))

=========Default=========
761 ns ± 5.85 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
2.07 µs ± 238 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[1, 1, 1, 1, 1], [0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [0, 0, 0, 0, 0], [1, 1, 1, 1, 1]]
=========Numpy result=========
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]


## Exercise 10
*Завдання*: Вводиться числа n i m. Створити масив випадкових значень n×m і обчислити мінімальне, максимальне значення, середнє та середньо квадратичне відхилення, округлене до 3 знаків після коми.

In [16]:
import math


def generate_random_matrix_default(n, m=n, upper_bound=100):
    result = []

    for i in range(n):
        row = []

        for j in range(m):
            row.append(np.random.randint(upper_bound))

        result.append(row)

    return result


def exercise_10_default(n, m):
    matrix = generate_random_matrix_default(n, m)

    print("Matrix:")
    print(matrix)

    min_value = min(min(matrix[i]) for i in range(n))
    max_value = max(max(matrix[i]) for i in range(n))
    sum_value = sum(sum(matrix[i]) for i in range(n))
    mean = sum_value / (n * m)
    sqr_diff = sum((matrix[i][j] - mean) ** 2 for i in range(n) for j in range(m))
    std_dev = math.sqrt(sqr_diff / (n * m))

    print(f"Min: {min_value}")
    print(f"Max: {max_value}")
    print(f"Mean: {mean:.3f}")
    print(f"Standard deviation: {std_dev:.3f}")


def exercise_10_numpy(n, m):
    matrix = np.random.randint(0, 100, size=(n, m))

    print("Matrix:")
    print(matrix)

    print(f"Min: {np.min(matrix)}")
    print(f"Max: {np.max(matrix)}")
    print(f"Mean: {np.mean(matrix):.3f}")
    print(f"Standard deviation: {np.std(matrix):.3f}")


n, m = (3, 4)

print("=========Default=========")
%time exercise_10_default(n, m)

print("=========Numpy=========")
%time exercise_10_numpy(n, m)

=========Default=========
Matrix:
[[75, 57, 93, 14], [56, 70, 16, 30], [76, 55, 91, 36]]
Min: 14
Max: 93
Mean: 55.750
Standard deviation: 25.807
CPU times: total: 0 ns
Wall time: 0 ns
=========Numpy=========
Matrix:
[[ 2 58 93 69]
 [47 42 25 92]
 [37 96 36 96]]
Min: 2
Max: 96
Mean: 57.750
Standard deviation: 30.161
CPU times: total: 0 ns
Wall time: 0 ns


## Exercise 12
*Завдання*: Створити масив одиниць розміром n×n та створити в ньому «рамку», що утворюється з 0.

In [17]:
def exercise_12_default(n):
    result = []

    for i in range(n):
        row_to_append = [0] * n if (i == 0 or i == n - 1) else [0] + [1] * (n - 2) + [0]
        result.append(row_to_append)

    return result


def exercise_12_numpy(n):
    result = np.ones((n, n), dtype=int)

    result[0] = np.zeros(n, dtype=int)
    result[-1] = np.zeros(n, dtype=int)
    result[:, 0] = np.zeros(n, dtype=int)
    result[:, -1] = np.zeros(n, dtype=int)

    return result

n = 5

print("=========Default=========")
%timeit -n 1000 exercise_12_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_12_numpy(n)

print("=========Default result=========")
print(exercise_12_default(n))

print("=========Numpy result=========")
print(exercise_12_numpy(n))

=========Default=========
1.07 µs ± 4.41 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
3.67 µs ± 429 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[0, 0, 0, 0, 0], [0, 1, 1, 1, 0], [0, 1, 1, 1, 0], [0, 1, 1, 1, 0], [0, 0, 0, 0, 0]]
=========Numpy result=========
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


## Exercise 16
*Завдання*: Заповнити вектор значеннями від 0 до n. Всі значення, що більші за n/4 та менші за 3n/4 замінити нулями.

In [18]:
def exercise_16_default(n):
    return [0 if (n / 4 < i < (3 * n) / 4) else i for i in range(n + 1)]


def exercise_16_numpy(n):
    result = np.arange(n + 1)
    result[(result > n / 4) & (result < (3 * n) / 4)] = 0

    return result

n = 10

print("=========Default=========")
%timeit -n 1000 exercise_16_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_16_numpy(n)

print("=========Default result=========")
print(exercise_16_default(n))

print("=========Numpy result=========")
print(exercise_16_numpy(n))

=========Default=========
1.26 µs ± 7.28 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
3.94 µs ± 931 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[0, 1, 2, 0, 0, 0, 0, 0, 8, 9, 10]
=========Numpy result=========
[ 0  1  2  0  0  0  0  0  8  9 10]


## Exercise 17
*Завдання*: Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значень, що менші за n/2 та більші за 3n/4 на протилежні.

In [19]:
def exercise_17_default(n):
    return [-1 * i if (i < n / 2 or i > (3 * n) / 4 ) else i for i in range(n + 1)]


def exercise_17_numpy(n):
    result = np.arange(n + 1)
    result[(result < n / 2) | (result > (3 * n) / 4)] *= -1

    return result

n = 10

print("=========Default=========")
%timeit -n 1000 exercise_17_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_17_numpy(n)

print("=========Default result=========")
print(exercise_17_default(n))

print("=========Numpy result=========")
print(exercise_17_numpy(n))

=========Default=========
1.33 µs ± 156 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
5.15 µs ± 640 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[0, -1, -2, -3, -4, 5, 6, 7, -8, -9, -10]
=========Numpy result=========
[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]


# Exercise 21
*Завдання*: Ввести числа n і m. Згенерувати матрицю n×n випадкових цілих елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці на протилежні за знаком.

In [20]:
def exercise_21_default(n, m):
    matrix = generate_random_matrix_default(n, n, m)

    print("Matrix:")
    print(matrix)

    max_elem = max(max(matrix[i]) for i in range(n))

    for i in range(n):
        for j in range(n):
            if matrix[i][j] == max_elem:
                matrix[i][j] *= -1

    print("Changed matrix:")
    print(matrix)


def exercise_21_numpy(n, m):
    matrix = np.random.randint(0, m + 1, size=(n, n))

    print("Matrix:")
    print(matrix)

    max_elem = np.max(matrix)
    matrix[matrix == max_elem] *= -1

    print("Changed matrix:")
    print(matrix)


n, m = (3, 100)


print("=========Default=========")
%time exercise_21_default(n, m)

print("=========Numpy=========")
%time exercise_21_numpy(n, m)

=========Default=========
Matrix:
[[26, 58, 22], [5, 28, 48], [76, 9, 96]]
Changed matrix:
[[26, 58, 22], [5, 28, 48], [76, 9, -96]]
CPU times: total: 0 ns
Wall time: 0 ns
=========Numpy=========
Matrix:
[[59 94 81]
 [75 57 99]
 [74 90  5]]
Changed matrix:
[[ 59  94  81]
 [ 75  57 -99]
 [ 74  90   5]]
CPU times: total: 0 ns
Wall time: 499 µs


# Task 2

*Завдання*: 2. Розв’язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:
- матричного множення;
- оберненої матриці;
- функції `numpy.linalg.solve()`.


\begin{align*}
\begin{cases}
2x_1 - x_2 + 3x_3 + 2x_4 &= 4 \\
3x_1 + 3x_2 + 3x_3 + 2x_4 &= 6 \\
3x_1 - x_2 - x_3 + 2x_4 &= 6 \\
3x_1 - x_2 + 3x_3 - x_4 &= 6 \\
\end{cases}
\end{align*}

In [31]:
lhs = np.array([
    [2, -1, 3, 2],
    [3, 3, 3, 2],
    [3, -1, -1, 2],
    [3, -1, 3, -1],
])

rhs = np.array([4, 6, 6, 6])
expected_result = np.array([2, 0, 0, 0])

def solve_cramer(lhs_part, rhs_part):
    size = lhs_part.shape[0]
    result = np.zeros(size)
    det = np.linalg.det(lhs_part)

    if np.allclose(det, 0):
        print("Unable to solve system using Cramer's rule(determinant equals zero)")
        return None

    for i in range(size):
        matrix_i = np.copy(lhs_part)
        matrix_i[:, i] = np.copy(rhs_part)
        result[i] = np.linalg.det(matrix_i) / det

    return result


print("Lhs part: ")
print(lhs)

print("Rhs part: ")
print(rhs)

cramer_result = solve_cramer(lhs, rhs)
numpy_result = np.linalg.solve(lhs, rhs)

print("Cramer's rule result: ")
print(cramer_result)

print("Numpy result: ")
print(cramer_result)

print("Checking Cramer's result, multiplying lhs to result(using np.allclose): ")
print(np.allclose(lhs @ cramer_result, rhs))

print("Checking Cramer's result, using inverse matrix(using np.allclose): ")
print(np.allclose(np.linalg.inv(lhs) @ rhs, expected_result))

Lhs part: 
[[ 2 -1  3  2]
 [ 3  3  3  2]
 [ 3 -1 -1  2]
 [ 3 -1  3 -1]]
Rhs part: 
[4 6 6 6]
Cramer's rule result: 
[2. 0. 0. 0.]
Numpy result: 
[2. 0. 0. 0.]
Checking Cramer's result, multiplying lhs to result(using np.allclose): 
True
Checking Cramer's result, using inverse matrix(using np.allclose): 
True
