# Task 1

## Exercise 1
*Завдання*: Вводиться число n. Вивести масив розміру n×n, в якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [45]:
import numpy as np


def exercise_1_default(n):
    result = []

    for i in range(n):
        row = []

        for j in range(n):
            value_to_append = i + 1 if i == j else 0
            row.append(value_to_append)

        result.append(row)

    return result


def exercise_1_numpy(n):
    return np.diag(np.arange(1, n + 1, 1))


n = 10

print("=========Default=========")
%timeit -n 1000 exercise_1_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_1_numpy(n)

print("=========Default result=========")
print(exercise_1_default(n))

print("=========Numpy result=========")
print(exercise_1_numpy(n))

=========Default=========
7.29 µs ± 713 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
2.28 µs ± 429 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 3, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 4, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 5, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 6, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 7, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 8, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 9, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 10]]
=========Numpy result=========
[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


## Exercise 3
*Завдання*: Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [46]:
def exercise_3_default(n, m, r, c):
    result = []

    for i in range(n):
        row = []

        for j in range(m):
            value_to_append = 0 if (i % r == 0 or j % c == 0) else 1
            row.append(value_to_append)

        result.append(row)

    return result


def exercise_3_numpy(n, m, r, c):
    result = np.ones((n, m), dtype=int)
    result[::r, :] = 0
    result[:, ::c] = 0

    return result


n, m, r, c = (6, 7, 2, 3)


print("=========Default=========")
%timeit -n 1000 exercise_3_default(n, m, r, c)

print("=========Numpy=========")
%timeit -n 1000 exercise_3_numpy(n, m, r, c)

print("=========Default result=========")
print(exercise_3_default(n, m, r, c))

print("=========Numpy result=========")
print(exercise_3_numpy(n, m, r, c))

=========Default=========
4.23 µs ± 340 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
2.39 µs ± 55.9 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 1, 1, 0], [0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 1, 1, 0], [0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 1, 1, 0]]
=========Numpy result=========
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


## Exercise 4
*Завдання*: Вводяться числа n і m. Вивести масив розміру n×m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m–1, а всі інші елементи матриці дорівнюють 0.

In [47]:
def exercise_4_default(n, m):
    result = []

    for i in range(m):
        row_to_append = [idx for idx in range(n)] if i == 0 else [0] * n
        result.append(row_to_append)

    return result


def exercise_4_numpy(n, m):
    result = np.zeros((m, n), dtype=int)
    result[0] = np.arange(n)

    return result


n, m = (3, 4)

print("=========Default=========")
%timeit -n 1000 exercise_4_default(n, m)

print("=========Numpy=========")
%timeit -n 1000 exercise_4_numpy(n, m)

print("=========Default result=========")
print(exercise_4_default(n, m))

print("=========Numpy result=========")
print(exercise_4_numpy(n, m))

=========Default=========
786 ns ± 7.95 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
1.14 µs ± 149 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[0, 1, 2], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
=========Numpy result=========
[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


## Exercise 5
*Завдання*: Вводиться число n. Вивести масив розміру n×n, в якому в рядках з парними індексами стоять 1, а в інших – 0.

In [48]:
def exercise_5_default(n):
    result = []

    for i in range(n):
        row_to_append = ([1] if i % 2 == 0 else [0]) * n
        result.append(row_to_append)

    return result


def exercise_5_numpy(n):
    result = np.zeros((n, n), dtype=int)
    result[::2] = np.ones(n, dtype=int)

    return result


n = 5

print("=========Default=========")
%timeit -n 1000 exercise_5_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_5_numpy(n)

print("=========Default result=========")
print(exercise_5_default(n))

print("=========Numpy result=========")
print(exercise_5_numpy(n))

=========Default=========
813 ns ± 75.6 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
1.99 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[1, 1, 1, 1, 1], [0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [0, 0, 0, 0, 0], [1, 1, 1, 1, 1]]
=========Numpy result=========
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]


## Exercise 10
*Завдання*: Вводиться числа n i m. Створити масив випадкових значень n×m і обчислити мінімальне, максимальне значення, середнє та середньо квадратичне відхилення, округлене до 3 знаків після коми.

In [49]:
import math


def generate_random_matrix_default(n, m=n, upper_bound=100):
    result = []

    for i in range(n):
        row = []

        for j in range(m):
            row.append(np.random.randint(upper_bound))

        result.append(row)

    return result


def exercise_10_default(n, m):
    matrix = generate_random_matrix_default(n, m)

    print("Matrix:")
    print(matrix)

    min_value = min(min(matrix[i]) for i in range(n))
    max_value = max(max(matrix[i]) for i in range(n))
    sum_value = sum(sum(matrix[i]) for i in range(n))
    mean = sum_value / (n * m)
    sqr_diff = sum((matrix[i][j] - mean) ** 2 for i in range(n) for j in range(m))
    std_dev = math.sqrt(sqr_diff / (n * m))

    print(f"Min: {min_value}")
    print(f"Max: {max_value}")
    print(f"Mean: {mean:.3f}")
    print(f"Standard deviation: {std_dev:.3f}")


def exercise_10_numpy(n, m):
    matrix = np.random.randint(0, 100, size=(n, m))

    print("Matrix:")
    print(matrix)

    print(f"Min: {np.min(matrix)}")
    print(f"Max: {np.max(matrix)}")
    print(f"Mean: {np.mean(matrix):.3f}")
    print(f"Standard deviation: {np.std(matrix):.3f}")


n, m = (3, 4)

print("=========Default=========")
%time exercise_10_default(n, m)

print("=========Numpy=========")
%time exercise_10_numpy(n, m)

=========Default=========
Matrix:
[[64, 64, 67, 11], [89, 10, 83, 62], [13, 33, 85, 16]]
Min: 10
Max: 89
Mean: 49.750
Standard deviation: 29.713
CPU times: total: 0 ns
Wall time: 0 ns
=========Numpy=========
Matrix:
[[91 13 35  9]
 [63 79 44 81]
 [83 79 70 63]]
Min: 9
Max: 91
Mean: 59.167
Standard deviation: 26.542
CPU times: total: 0 ns
Wall time: 499 µs


## Exercise 12
*Завдання*: Створити масив одиниць розміром n×n та створити в ньому «рамку», що утворюється з 0.

In [50]:
def exercise_12_default(n):
    result = []

    for i in range(n):
        row_to_append = [0] * n if (i == 0 or i == n - 1) else [0] + [1] * (n - 2) + [0]
        result.append(row_to_append)

    return result


def exercise_12_numpy(n):
    result = np.ones((n, n), dtype=int)

    result[0] = np.zeros(n, dtype=int)
    result[-1] = np.zeros(n, dtype=int)
    result[:, 0] = np.zeros(n, dtype=int)
    result[:, -1] = np.zeros(n, dtype=int)

    return result

n = 5

print("=========Default=========")
%timeit -n 1000 exercise_12_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_12_numpy(n)

print("=========Default result=========")
print(exercise_12_default(n))

print("=========Numpy result=========")
print(exercise_12_numpy(n))

=========Default=========
1.08 µs ± 58.6 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
3.52 µs ± 55.4 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[0, 0, 0, 0, 0], [0, 1, 1, 1, 0], [0, 1, 1, 1, 0], [0, 1, 1, 1, 0], [0, 0, 0, 0, 0]]
=========Numpy result=========
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


## Exercise 16
*Завдання*: Заповнити вектор значеннями від 0 до n. Всі значення, що більші за n/4 та менші за 3n/4 замінити нулями.

In [51]:
def exercise_16_default(n):
    return [0 if (n / 4 < i < (3 * n) / 4) else i for i in range(n + 1)]


def exercise_16_numpy(n):
    result = np.arange(n + 1)
    result[(result > n / 4) & (result < (3 * n) / 4)] = 0

    return result

n = 10

print("=========Default=========")
%timeit -n 1000 exercise_16_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_16_numpy(n)

print("=========Default result=========")
print(exercise_16_default(n))

print("=========Numpy result=========")
print(exercise_16_numpy(n))

=========Default=========
1.27 µs ± 14.6 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
3.61 µs ± 410 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[0, 1, 2, 0, 0, 0, 0, 0, 8, 9, 10]
=========Numpy result=========
[ 0  1  2  0  0  0  0  0  8  9 10]


## Exercise 17
*Завдання*: Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значень, що менші за n/2 та більші за 3n/4 на протилежні.

In [52]:
def exercise_17_default(n):
    return [-1 * i if (i < n / 2 or i > (3 * n) / 4 ) else i for i in range(n + 1)]


def exercise_17_numpy(n):
    result = np.arange(n + 1)
    result[(result < n / 2) | (result > (3 * n) / 4)] *= -1

    return result

n = 10

print("=========Default=========")
%timeit -n 1000 exercise_17_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_17_numpy(n)

print("=========Default result=========")
print(exercise_17_default(n))

print("=========Numpy result=========")
print(exercise_17_numpy(n))

=========Default=========
1.25 µs ± 22.6 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
4.73 µs ± 654 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[0, -1, -2, -3, -4, 5, 6, 7, -8, -9, -10]
=========Numpy result=========
[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]


# Exercise 21
*Завдання*: Ввести числа n і m. Згенерувати матрицю n×n випадкових цілих елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці на протилежні за знаком.

In [53]:
def exercise_21_default(n, m):
    matrix = generate_random_matrix_default(n, n, m)

    print("Matrix:")
    print(matrix)

    max_elem = max(max(matrix[i]) for i in range(n))

    for i in range(n):
        for j in range(n):
            if matrix[i][j] == max_elem:
                matrix[i][j] *= -1

    print("Changed matrix:")
    print(matrix)


def exercise_21_numpy(n, m):
    matrix = np.random.randint(0, m + 1, size=(n, n))

    print("Matrix:")
    print(matrix)

    max_elem = np.max(matrix)
    matrix[matrix == max_elem] *= -1

    print("Changed matrix:")
    print(matrix)


n, m = (3, 100)


print("=========Default=========")
%time exercise_21_default(n, m)

print("=========Numpy=========")
%time exercise_21_numpy(n, m)

=========Default=========
Matrix:
[[30, 70, 0], [57, 19, 27], [95, 51, 40]]
Changed matrix:
[[30, 70, 0], [57, 19, 27], [-95, 51, 40]]
CPU times: total: 0 ns
Wall time: 0 ns
=========Numpy=========
Matrix:
[[50 69 54]
 [19 75 17]
 [81 43 81]]
Changed matrix:
[[ 50  69  54]
 [ 19  75  17]
 [-81  43 -81]]
CPU times: total: 0 ns
Wall time: 500 µs


# Task 2

*Завдання*: Розв’язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:
- матричного множення;
- оберненої матриці;
- функції `numpy.linalg.solve()`.


\begin{align*}
\begin{cases}
2x_1 - x_2 + 3x_3 + 2x_4 &= 4 \\
3x_1 + 3x_2 + 3x_3 + 2x_4 &= 6 \\
3x_1 - x_2 - x_3 + 2x_4 &= 6 \\
3x_1 - x_2 + 3x_3 - x_4 &= 6 \\
\end{cases}
\end{align*}

In [54]:
lhs = np.array([
    [2, -1, 3, 2],
    [3, 3, 3, 2],
    [3, -1, -1, 2],
    [3, -1, 3, -1],
])

rhs = np.array([4, 6, 6, 6])
expected_result = np.array([2, 0, 0, 0])

def solve_cramer(lhs_part, rhs_part):
    size = lhs_part.shape[0]
    result = np.zeros(size)
    det = np.linalg.det(lhs_part)

    if np.allclose(det, 0):
        print("Unable to solve system using Cramer's rule(determinant equals zero)")
        return None

    for i in range(size):
        matrix_i = np.copy(lhs_part)
        matrix_i[:, i] = np.copy(rhs_part)
        result[i] = np.linalg.det(matrix_i) / det

    return result


print("Lhs part: ")
print(lhs)

print("Rhs part: ")
print(rhs)

cramer_result = solve_cramer(lhs, rhs)
numpy_result = np.linalg.solve(lhs, rhs)

print("Cramer's rule result: ")
print(cramer_result)

print("Numpy result: ")
print(cramer_result)

print("Checking Cramer's result, multiplying lhs to result(using np.allclose): ")
print(np.allclose(lhs @ cramer_result, rhs))

print("Checking Cramer's result, using inverse matrix(using np.allclose): ")
print(np.allclose(np.linalg.inv(lhs) @ rhs, expected_result))

Lhs part: 
[[ 2 -1  3  2]
 [ 3  3  3  2]
 [ 3 -1 -1  2]
 [ 3 -1  3 -1]]
Rhs part: 
[4 6 6 6]
Cramer's rule result: 
[2. 0. 0. 0.]
Numpy result: 
[2. 0. 0. 0.]
Checking Cramer's result, multiplying lhs to result(using np.allclose): 
True
Checking Cramer's result, using inverse matrix(using np.allclose): 
True


# Task 3
*Завдання*: Обчислити значення матричного виразу $(A - B)A + 3B$, де


\begin{align*}
A &= \begin{pmatrix}
    3 & 2 & -5 \\
    4 & 2 & 0 \\
    1 & 1 & 2
\end{pmatrix} \\
B &= \begin{pmatrix}
    -1 & 2 & 4 \\
    0 & 3 & 2 \\
    -1 & -3 & 4
\end{pmatrix}
\end{align*}

In [55]:
def add_matrices(lhs, rhs):
    if len(lhs) != len(rhs) or len(lhs[0]) != len(rhs[0]):
        print("Can't add matrices(wrong dimensions)")
        return None

    n, m = (len(lhs), len(lhs[0]))

    result = [[0 for _ in range(len(lhs[0]))] for _ in range(len(lhs))]

    for i in range(n):
        for j in range(m):
            result[i][j] = lhs[i][j] + rhs[i][j]

    return result


def multiply_matrices(lhs, rhs):
    if len(lhs[0]) != len(rhs):
        print("Can't multiply matrices(wrong dimensions)")
        return None

    n, m, k = (len(lhs), len(lhs[0]), len(rhs[0]))

    result = [[0 for _ in range(k)] for _ in range(n)]

    for i in range(n):
        for j in range(k):
            for p in range(k):
                result[i][j] += lhs[i][p] * rhs[p][j]

    return result


def multiply_scalar(matrix, number):
    n, m = (len(matrix), len(matrix[0]))

    return [[matrix[i][j] * number for j in range(m)] for i in range(n)]


def task_3_default():
    A = [
        [3, 2, -5],
        [4, 2, 0],
        [1, 1, 2]
    ]

    B = [
        [-1, 2, 4],
        [0, 3, 2],
        [-1, -3, 4]
    ]

    return add_matrices(multiply_matrices(add_matrices(A, multiply_scalar(B, -1)), A), multiply_scalar(B, 3))


def task_3_numpy():
    A = np.array([
        [3, 2, -5],
        [4, 2, 0],
        [1, 1, 2]
    ])

    B = np.array([
        [-1, 2, 4],
        [0, 3, 2],
        [-1, -3, 4]
    ])

    return (A - B) @ A + 3 * B


print("=========Default=========")
%timeit -n 1000 task_3_default()

print("=========Numpy=========")
%timeit -n 1000 task_3_numpy()

default_result = task_3_default()
numpy_result = task_3_numpy()

print("=========Default result=========")
print(default_result)
print("=========Numpy result=========")
print(numpy_result)

print("=========np.allclose=========")
print(np.allclose(default_result, numpy_result))


=========Default=========
12.7 µs ± 368 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Numpy=========
5.11 µs ± 200 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
=========Default result=========
[[0, 5, -26], [6, 13, -18], [17, 1, -2]]
=========Numpy result=========
[[  0   5 -26]
 [  6  13 -18]
 [ 17   1  -2]]
=========np.allclose=========
True
